import Navbar from '@/components/header/Navbar';
import './global.css';

export const metadata = {
  title: 'Apache Age',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
